# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_cl:
   - dapplion
   - wemeetagain
   - tuyennhv
   - g11tech
   - philknows
   - nazarhussain

# role: validator_keys
validator_keys_sync_files:
  - src: "{{ inventory_dir }}/files/validator_keys/{{ inventory_hostname }}/keys/"
    dest: "{{ lodestar_validator_datadir }}/keys/"
  - src: "{{ inventory_dir }}/files/validator_keys/{{ inventory_hostname }}/secrets/"
    dest: "{{ lodestar_validator_datadir }}/secrets/"

validator_bls_sync_files:
  - src: "{{ inventory_dir }}/files/validator_keys/{{ inventory_hostname }}/change_operations.json"
    dest: "{{ lodestar_validator_datadir }}/change_operations.json"
    owner: lodestar
    group: lodestar

# role: ethpandaops.general.ethereum_node
ethereum_node_cl: lodestar
lodestar_validator_metrics_port: 8111
# role: ethpandaops.general.lodestar
lodestar_container_name: beacon
lodestar_validator_container_name: validator
lodestar_container_image: "{{ default_ethereum_client_images.lodestar }}"
lodestar_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_beacon_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_cl_ports_http_beacon | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_beacon_hostname }}"
  NODE_OPTIONS: "--max-old-space-size=16384"
lodestar_container_volumes:
  - "{{ lodestar_datadir }}:/data"
  - "{{ lodestar_auth_jwt_path }}:/execution-auth.jwt:ro"
  - "{{ eth_testnet_config_dir }}:/network-config:ro"
lodestar_container_command_extra_args:
  - --paramsFile=/network-config/config.yaml
  - --genesisStateFile=/network-config/genesis.ssz
  - --bootnodes={{ ethereum_cl_bootnodes | join(',') }}
  - --rest.namespace="*"
  - --network.connectToDiscv5Bootnodes
  - --nat=true
  - --network.useWorker
  - --deterministicLongLivedAttnets
  #- --chain.trustedSetup=/network-config/trusted_setup.txt
  #- --checkpointSyncUrl={{ checkpoint_sync_url }}
lodestar_validator_container_volumes:
  - "{{ lodestar_validator_datadir }}:/validator-data"
  - "{{ eth_testnet_config_dir }}:/network-config:ro"

lodestar_validator_container_ports:
  - "127.0.0.1:{{ lodestar_validator_metrics_port }}:{{ lodestar_validator_metrics_port }}"

lodestar_validator_container_command_extra_args:
  - --paramsFile=/network-config/config.yaml
  - --graffiti={{ ethereum_node_cl }}/{{ ethereum_node_el }}
  - --metrics
  - --metrics.port={{ lodestar_validator_metrics_port}}
  - --metrics.address=0.0.0.0

lodestar_validator_datadir: /data/lodestar-validator
lodestar_container_pull: true

# role: ethpandaops.general.prometheus
prometheus_remote_push_url: https://victoriametrics.ethdevops.io/insert/0/prometheus/api/v1/write
prometheus_remote_write_username: "{{ secret_prometheus_remote_write.username }}"
prometheus_remote_write_password: "{{ secret_prometheus_remote_write.password }}"
prometheus_config: |
  global:
    scrape_interval: 30s
    evaluation_interval: 30s
    scrape_timeout: 10s
    external_labels:
      instance: "{{ inventory_hostname }}"
      ip_address: "{{ ansible_host }}"
      network: "{{ ethereum_network_name }}"
      testnet: "{{ ethereum_network_name }}"
      execution_client: "{{ ethereum_node_el }}"
      consensus_client: "{{ ethereum_node_cl }}"
  remote_write:
    - queue_config:
        batch_send_deadline: 5s
        max_backoff: 500ms
        max_samples_per_send: 500
        min_backoff: 50ms
        max_shards: 100
      url: {{ prometheus_remote_push_url }}
      remote_timeout: 10s
      basic_auth:
        username: {{ prometheus_remote_write_username }}
        password: {{ prometheus_remote_write_password }}
  scrape_configs:
    - job_name: "prometheus"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["localhost:9090"]
          labels:
            instance: "{{ inventory_hostname }}"
    - job_name: "node"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["172.17.0.1:9100"]
          labels:
            instance: "{{ inventory_hostname }}"
    - job_name: "exporter"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["ethereum-metrics-exporter:9090"]
          labels:
            instance: "{{ inventory_hostname }}"
    - job_name: "consensus_node"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["{{ vars[ethereum_node_cl + '_container_name'] }}:{{ ethereum_node_cl_ports_metrics }}"]
          labels:
            instance: "{{ inventory_hostname }}"
    - job_name: "validator"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["validator:{{ lodestar_validator_metrics_port }}"]
          labels:
            instance: "{{ inventory_hostname }}"