gen_kubernetes_config_default_output_dir: ../kubernetes/{{ ethereum_network_name | replace('4844-', '') }}

default_cl_endpoint: >-
  http://{{ gen_kubernetes_config_ethereum_node.cl + '-' + gen_kubernetes_config_ethereum_node.el + '-' + gen_kubernetes_config_ethereum_node.value + ':' + ethereum_node_cl_ports_http_beacon | string }}
default_el_endpoint: >-
  http://{{ gen_kubernetes_config_ethereum_node.el + '-' + gen_kubernetes_config_ethereum_node.cl + '-' + gen_kubernetes_config_ethereum_node.value + ':' + ethereum_node_el_ports_http_rpc | string }}
default_el_ws_endpoint: >-
  ws://{{ gen_kubernetes_config_ethereum_node.el + '-' + gen_kubernetes_config_ethereum_node.cl + '-' + gen_kubernetes_config_ethereum_node.value + ':' + ethereum_node_el_ports_ws_rpc | string }}
default_el_auth_endpoint: >-
  http://{{ gen_kubernetes_config_ethereum_node.el + '-' + gen_kubernetes_config_ethereum_node.cl + '-' + gen_kubernetes_config_ethereum_node.value + ':' + ethereum_node_el_ports_engine | string }}

gen_kubernetes_config_ethereum_node:
  el: nethermind
  cl: lodestar
  value: "001"

gen_kubernetes_config_helm_repositories:
  - name: ethereum-helm-charts
    url: https://ethpandaops.github.io/ethereum-helm-charts
  - name: blobscan-helm-charts
    url: https://blobscan.github.io/blobscan-helm-charts/

gen_kubernetes_config_ethereum_node_name: "{{ gen_kubernetes_config_ethereum_node.cl }}-{{ gen_kubernetes_config_ethereum_node.el }}-{{ gen_kubernetes_config_ethereum_node.value }}"

gen_kubernetes_config_helm_charts:
  config:
    valuesTemplatePath: templates/config.yaml.j2
  beacon-metrics-gazer:
    valuesTemplatePath: templates/beacon-metrics-gazer.yaml.j2
    dependencies:
      - name: beacon-metrics-gazer
        repository: https://ethpandaops.github.io/ethereum-helm-charts
        version: 0.1.3
  blobscan:
    valuesTemplatePath: templates/blobscan.yaml.j2
    dependencies:
      - name: blobscan
        repository: https://blobscan.github.io/blobscan-helm-charts/
        version: 0.2.6
      - name: blobscan-api
        repository: https://blobscan.github.io/blobscan-helm-charts/
        version: 0.2.5
      - name: blobscan-indexer
        repository: https://blobscan.github.io/blobscan-helm-charts/
        version: 0.2.7
  blockscout:
    valuesTemplatePath: templates/blockscout.yaml.j2
    dependencies:
      - name: blockscout
        repository: https://ethpandaops.github.io/ethereum-helm-charts
        version: 0.2.0
  checkpointz:
    valuesTemplatePath: templates/checkpointz.yaml.j2
    dependencies:
      - name: checkpointz
        repository: https://ethpandaops.github.io/ethereum-helm-charts
        version: 0.1.3
  ethstats:
    valuesTemplatePath: templates/ethstats.yaml.j2
    dependencies:
      - name: ethstats
        repository: https://ethpandaops.github.io/ethereum-helm-charts
        version: 0.1.4
  faucet:
    valuesTemplatePath: templates/fauceth.yaml.j2
    dependencies:
      - name: fauceth
        repository: https://ethpandaops.github.io/ethereum-helm-charts
        version: 0.2.3
  faucet-2:
    valuesTemplatePath: templates/eth-faucet.yaml.j2
    dependencies:
      - name: eth-faucet
        repository: https://ethpandaops.github.io/ethereum-helm-charts
        version: 0.1.1
  forkmon:
    valuesTemplatePath: templates/forkmon.yaml.j2
    dependencies:
      - name: forkmon
        repository: https://ethpandaops.github.io/ethereum-helm-charts
        version: 0.1.4
  forky:
    valuesTemplatePath: templates/forky.yaml.j2
    dependencies:
      - name: forky
        repository: https://ethpandaops.github.io/ethereum-helm-charts
        version: 0.1.1
  homepage:
    valuesTemplatePath: templates/testnet-homepage.yaml.j2
    dependencies:
      - name: testnet-homepage
        repository: https://ethpandaops.github.io/ethereum-helm-charts
        version: 0.2.2
  rpc:
    valuesTemplatePath: templates/rpc-proxy.yaml.j2
    dependencies:
      - name: rpc-proxy
        repository: https://ethpandaops.github.io/ethereum-helm-charts
        version: 0.1.2
  "{{ gen_kubernetes_config_ethereum_node_name }}":
    valuesTemplatePath: templates/ethereum-node.yaml.j2
    dependencies:
      - name: ethereum-node
        repository: https://ethpandaops.github.io/ethereum-helm-charts
        version: 0.0.7
        alias: "{{ gen_kubernetes_config_ethereum_node_name }}"
